# Definição de variáveis
@base_url = https://humble-space-succotash-5gq75r55qgv9h59q-8080.app.github.dev


### Listar todos os veículos
GET {{base_url}}/api/veiculos
Content-Type: application/json

### Inserir novo veículo
POST {{base_url}}/api/veiculos
Content-Type: application/json

{
    "modelo": "Ferrari F12",
    "ano": 2022,
    "valor": 850000.00
}


### Inserir segundo veículo
POST {{base_url}}/api/veiculos
Content-Type: application/json

{
    "modelo": "Audi R8",
    "ano": 2024,
    "valor": 450000.00
}

### Inserir terceiro veículo
POST {{base_url}}/api/veiculos
Content-Type: application/json

{
    "modelo": "Lamborghini Aventador SVJ",
    "ano": 2023,
    "valor": 7000000.00
}


### Inserir quarto veículo
POST {{base_url}}/api/veiculos
Content-Type: application/json

{
    "modelo": "Ford Mustang",
    "ano": 2021,
    "valor": 750000.00
}

### Buscar veículo por ID
GET {{base_url}}/api/veiculos/1
Content-Type: application/json

### Deletar veículo
DELETE {{base_url}}/api/veiculos/1
Content-Type: application/json



