# Definição de variáveis
@base_url = https://jubilant-fiesta-q7q564g95gx5c9v4x-8080.app.github.dev


### Listar todos os veículos
GET {{base_url}}/api/veiculos
Content-Type: application/json

### Inserir novo veículo
POST {{base_url}}/api/veiculos
Content-Type: application/json

{
    "modelo": "Ferrari F12",
    "ano": 2025,
    "valor": 9195000.00
}

### Inserir segundo veículo
POST {{base_url}}/api/veiculos
Content-Type: application/json

{
    "modelo": "Lamborghini Aventador SVJ",
    "ano": 2023,
    "valor": 9185000.00
}

### Inserir terceiro veículo
POST {{base_url}}/api/veiculos
Content-Type: application/json

{
    "modelo": "Mustang",
    "ano": 2024,
    "valor": 1100000.00
}

### Inserir quarto veículo
POST {{base_url}}/api/veiculos
Content-Type: application/json

{
    "modelo": "Bugatti Chiron",
    "ano": 2021,
    "valor": 10075000.00
}

### Buscar veículo por ID
GET {{base_url}}/api/veiculos/1
Content-Type: application/json

### Deletar veículo
DELETE {{base_url}}/api/veiculos/1
Content-Type: application/json



